### ISSUE TITLE
Review comments not given for all changed files

### ISSUE THREAD

**Issue by vandnayadav1988** [anc95/ChatGPT-CodeReview#132]
Hi 
[anc95](https://github.com/anc95)
[PeterDaveHello](https://github.com/PeterDaveHello)
[jeonbyeongmin](https://github.com/jeonbyeongmin)
i changed 3 files and raised a PR https://github.com/vandnayadav1988/Hackathaon/pull/41
However, i am getting review comments only for 2 files and 3rd one is ignored. can you please help me out understand why this is happening? and if i can include the third file in the review?

**Comment by vandnayadav1988** [comment]
[anc95](https://github.com/anc95)

**Comment by anc95** [comment]
@vandnayadav1988 was this fixed?

**Comment by anc95** [comment]
@vandnayadav1988 I have check https://github.com/vandnayadav1988/Hackathaon/pull/41. the review comments was sent by the cr-gpt bot. I guess the cause is that, the bot server is deployed on aws lambda. there has a runtime time limit on the function execution of lambda, it's 1min. if the time needed exceeds 1 min, the left files are not processed and not reviewed.

**Comment by vandnayadav1988** [comment]
@anc95 : Thanks for explaining.
